Price_Monitor/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fabelio_price_monitor.urls')),
]

fabelio_price_monitor/urls.py
from django.urls import path
from . import views

app_name = 'fabelio_price_monitor'

# url's for fabelio price monitor app
urlpatterns = [
    path('', views.price_monitor_view, name='submit_link'),
    path('submitted_link/', views.submitted_link, name='submitted_link'),
    path('product/', views.product, name='product'),
    path('product/<title>', views.product, name='product')

]

fabelio_price_monitor/models.py
from django.db import models


# Django models for fabelio price monitor
class Product(models.Model):
    title = models.TextField(max_length=200)
    image = models.ImageField(width_field=100, height_field=100, null=True)
    url = models.TextField(max_length=600)
    current_price = models.TextField(max_length=200)
    description = models.TextField(max_length=2000)

    def __str__(self):
        return self.title

fabelio_price_monitor/forms.py
from django import forms
from .models import Product

# Django form for page 1 with text input box to get the product page link


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['url']
        widgets = {
            'url': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Submit your link ...'})
        }

fabelio_price_monitor/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from urllib.parse import quote
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
from .models import Product
from .forms import AddProductForm


# view for page 1
# @param request
# @return render product page or submitted link page if url already existed
def price_monitor_view(request):
    products = Product.objects.all()
    form = AddProductForm(request.POST)
    try:
        if request.method == 'POST':
            if form.is_valid():
                # get the url from the form
                url = form.cleaned_data.get('url')
                for product in products:
                    # redirect to page 2 (submitted link page) if the link already submitted before
                    if url == product.url:
                        return HttpResponseRedirect('submitted_link')
                data = get_data(url)
                Product.objects.create(
                    url=url,
                    title=data['title'],
                    current_price=data['current_price'],
                    description=data['description'],
                )
                # redirect to page 3 (product page) after submitting the product page link
                return HttpResponseRedirect('product/'+data['title'])
    except ValueError:
        return HttpResponseRedirect('/')
    except IndexError:

        return HttpResponseRedirect('/')
    else:
        form = AddProductForm()
    context = {
        'form': form,
    }

    submit_link = "page_1.html"
    return render(request, submit_link, context)


# view for page 2
# @param request
# @return render submitted link page
def submitted_link(request):
    products = Product.objects.order_by('-id')
    context = {
        'products': products,
    }
    return render(request, 'page_2.html', context)

# view for page 3, get title parameter from url
# @param request,title
# @return render product page


def product(request, title=None):
    product = None
    products = Product.objects.all()
    for product in products:
        # check if title exist in database
        if title:
            # return product with the same title with the parameter
            product = Product.objects.get(title=title)

        else:
            # if doesnt exist return none
            product = None
    context = {
        'product': product,
    }
    return render(request, 'page_3.html', context)


# get data from url, parsing fabelio product page
# @param url
# @return product object for Django models
def get_data(url):
    req = Request(url, headers={
                  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36'})
    html = urlopen(req).read()
    # initialize beautifulsoup
    soup = BeautifulSoup(html, 'html.parser')
    # find product title
    title = soup.find_all(
        'h1', {"class": "page-title"})[0].find('span').get_text()
    # find product current price
    current_price = soup.find_all(
        'span', {"class": "price"})[0].get_text()
    # find product description
    description = soup.find('div', id="description").get_text()

    # image = soup.find_all('div', {"class": "product media"})
    # print(image)
    return {'title': title, 'current_price': current_price, 'description': description}

fabelio_price_monitor/templates/base.html
{% load static %}
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Price Monitor</title>
  </head>

  <body>
    <div class="header">
      <div class="logo">prima.</div>
      <a href="{% url 'fabelio_price_monitor:submit_link' %}">Submit Link</a>
      <a href="{% url 'fabelio_price_monitor:submitted_link' %}"
        >Submitted Link</a
      >
      <a href="{% url 'fabelio_price_monitor:product' %}">Product</a>
    </div>
    {% block content %} {% endblock %}
  </body>
</html>

fabelio_price_monitor/templates/page_1.html
{% extends 'base.html' %} {% block content %} {% load widget_tweaks %}
<div class="body-content">
  <div class="welcome-text">
    Welcome,
  </div>
  <div class="submit-your-link-text">
    Please submit your product page link below!
  </div>
  <form action="" method="POST" id="input-link">
    {% csrf_token %} {% render_field form.url class="input" %}
  </form>
  <button type="submit" id="submit" class="submit-button" form="input-link">
    Submit
  </button>
</div>
{% endblock%}

fabelio_price_monitor/templates/page_2.html
{% extends 'base.html' %} {% block content %}
<h1 class="page2-text">Submitted Link</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Link</th>
      <th scope="col">Product Name</th>
      <th scope="col">Last Price</th>
      <th scope="col">Product</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr>
      <td>{{product.url}}</td>
      <td>{{product.title}}</td>
      <td>{{product.current_price}}</td>
      <td>
        <a href="{% url 'fabelio_price_monitor:product' title=product.title %}"
          >{{product.title}}
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

fabelio_price_monitor/templates/page_3.html
{% extends 'base.html' %} {%block content%}

  {% if product is not None %}
  <div class="body-content2">
  <h1>{{product.title}}</h1>
  <h2>{{product.current_price}}</h2>
  <p>
    {{product.description}}
  </p>
</div>
      {% else %}
      <div class="no-product">
      <h1 >No Product to Display</h1>
      </div>
      {% endif %}
    

    {% endblock %}
</div>